# Netlify Configuration for FREE hosting
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all API calls to Render backend
[[redirects]]
  from = "/api/*"
  to = "https://cely-pets-api.onrender.com/api/:splat"
  status = 200
  force = true

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Form handling (FREE feature)
[[forms]]
  name = "contact"
